apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-converter-api-deployment
spec:
  replicas: 2
  selector:
     matchLabels: 
        app: currency-converter-api
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: currency-converter-api
    spec:     # pod spec                  
      containers: 
      - name: currency-converter-api
        image: gcr.io/curr-converter-23009/currency-converter-api-image:v1 # image we pushed
        ports:
        - containerPort: 4000