apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.appName}}
spec:
    type: LoadBalancer
    selector: 
        app: {{ .Values.appName}}
    ports:
        - protocol: {{ .Values.loadBalancer.protocol}}
          port: {{ .Values.loadBalancer.port}}
          targetPort: {{ .Values.loadBalancer.targetPort}}
